package io.mosip.digitalcard.constant;

import javax.annotation.Resource;

public enum ApiName {
    CRYPTOMANAGER_ENCRYPT, CRYPTOMANAGER_DECRYPT, TEMPLATES, IDREPOGETIDBYUIN, PDFSIGN, CREATEDATASHARE,CREDENTIAL_REQ_URL,CREDENTIAL_STATUS_URL
}
